name: Setup boilerplate

on:
  workflow_dispatch:
    inputs:
      boilerplate:
        type: choice
        description: Name of boilerplate
        options:
        - backend-boilerplate-php-laravel
        - backend-boilerplate-expressjs
        - backend-boilerplate-nestjs
        - backend-boilerplate-hapi-js
        - backend-boilerplate-dotnet
        - backend-boilerplate-java-springboot
        - backend-boilerplate-java-spring-webflux
        - backend-boilerplate-kotlin-springboot
        - backend-boilerplate-golang
        - backend-boilerplate-ruby
        - backend-boilerplate-django
        - backend-boilerplate-fastapi
        - backend-boilerplate-flask
        - backend-boilerplate-sanic
        required: true
      branch-name:
        type: string
        description: Name of the branch to initialize boilerplate in
        required: true
        default: implementation


jobs:
  setup-boilerplate:
    name: Setup boilerplate
    uses: DevSkillsHQ/setup-boilerplate-workflow/.github/workflows/setup-boilerplate.yml@cypress12
    permissions:
      contents: write
    with:
      boilerplate: ${{ github.event.inputs.boilerplate }}
      branch-name: ${{ github.event.inputs.branch-name }}